### PR TITLE
Upgrade kube ping version

### PR DESCRIPTION
**Pull request by hectorj2f**
- TODO:
- [x] Test that everything works without errors related to this new version

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Why is it WIP?

**Comment by hectorj2f** [comment]
@bartoszmajsak bc I am testing it that doesn't cause any error in comparison with our current version. That  is all :)

**Comment by hectorj2f** [comment]
We're good cause we don't get any error related to kube ping. All we get are related to other parts of keycloak.

**Comment by hectorj2f** [comment]
ping @bartoszmajsak :D

**Comment by hectorj2f** [comment]
[test]

**Review by alexeykazakov — APPROVED** [review]

**Pull request merged**
