### PR TITLE
fix(db) address all the issues to successfully migrate 3.1.X-CR1-Snapshot to 3.2.0 Final version

### PR DESCRIPTION
**Pull request by hectorj2f**
related to https://github.com/fabric8-services/fabric8-auth/issues/1

Tested scenarion in keycloak-cluster-test project:
- [x] Create an empty db
- [x] Deploy current standalone version of KC
- [x] Run the new KC instance containing the scripts
- [x] Check basic functionality of KC
- [x] Check image changes using a core (using f8-platform)

Actions pre-deployment: 
- [x] Need to do a bkp of prod-preview kc
- [x] Deploy the new image

### CODE REVIEW

**Comment by alexeykazakov** [comment]
Related to https://github.com/fabric8-services/fabric8-auth/issues/1

**Comment by hectorj2f** [comment]
@sbose78 did you check the changes related to the section `Migrating to 3.2.0` such as `openid` ? https://keycloak.gitbooks.io/documentation/server_admin/topics/MigrationFromOlderVersions.html

**Comment by hectorj2f** [comment]
I am happy with the PR but I didn't tests all the functionalities used by core. I tested login/logout, creation of spaces, creation of wis...

**Review by alexeykazakov — APPROVED** [review]
LGTM. Let's ask the SD team to do an extra back up and apply it!

**Comment by sbose78** [comment]
Just to be clear, these are the 2 files where the sql changes were present originally :  

- https://github.com/keycloak/keycloak/blob/3.2.0.Final/server-spi-private/src/main/java/org/keycloak/migration/migrators/MigrateTo3_2_0.java
- https://github.com/keycloak/keycloak/blob/3.2.0.Final/model/jpa/src/main/resources/META-INF/jpa-changelog-3.2.0.xml


Unable to find the SQLs for the below  - could you point me to them please ?
https://github.com/keycloak/keycloak/blob/3.2.0.Final/server-spi-private/src/main/java/org/keycloak/migration/migrators/MigrateTo3_2_0.java#L62

```
 RoleModel queryClients = realmAccess.addRole(AdminRoles.QUERY_CLIENTS);
        RoleModel queryUsers = realmAccess.addRole(AdminRoles.QUERY_USERS);
        RoleModel queryGroups = realmAccess.addRole(AdminRoles.QUERY_GROUPS);

        RoleModel viewClients = realmAccess.getRole(AdminRoles.VIEW_CLIENTS);
        if (viewClients != null) {
            viewClients.addCompositeRole(queryClients);
        }
        RoleModel viewUsers = realmAccess.getRole(AdminRoles.VIEW_USERS);
        if (viewUsers != null) {
            viewUsers.addCompositeRole(queryUsers);
            viewUsers.addCompositeRole(queryGroups);
}
```

or would it be manual step?

**Comment by hectorj2f** [comment]
@sbose78 what I did it was to perform a manual migration following KC instructions. That generates a sql script which is the one I used as template. The problem is that even running this sql script wasn't enough cause this scripts doesn't take into account things such as `IF EXISTS`. So this sql script will fail, what I did it was to revert our changes (creating temp columns, renaming indexes for a while,... ). To achieve a successful migration using kc update migration strategy. To do so, I had to create a pre-update and post-update scripts.

**Pull request merged**
